#!/bin/bash
#
#  media-utils - Utilities for media files manipulation
#  Copyright (C) 2010, Eduardo Antunes C. de Sousa
#
#  This file is part of media-utils.
#
#  media-utils is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  media-utils is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with media-utils.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: Eduardo Antunes C. de Sousa <ecsousa@gmail.com>
#

IFS='
';

for dir in $1; do

  echo Unpacking $dir...

  if [ ! -e $dir/*.rar ]; then
    files=($(ls -d $dir/*.avi $dir/*.mkv $dir/*.mp4 2>/dev/null));

    mc=$2;
    while [ "$mc" != "m" -a "$mc" != "c" ]; do
      read -p 'No rar found, will try raw files. Type c to copy, or m to move: ' -n1 mc;
  	echo;
    done;

    if [ "$mc" == "m" ]; then
      mv $files . -v
    else
      cp $files . -v
    fi;

  #files=($(ls -d $dir/*.avi $dir/*.mkv $dir/*.mp4 2>/dev/null | sed -e 's/.*\///'));

  else

    rar=`ls $dir/*.rar | sed -ne '1p'`
    files=($(unrar lb $rar | sed -ne '/.*\.\(avi\|mkv\|mp4\)$/p'))

    unrar e $rar $files
  fi;

  count=0

  for file in $files
  do
    file=`basename $file`;

      if [ $count == 0 ]
      then
        if [ $file != `basename $dir`${file[@]:`expr ${#file} - 4`} ]
        then
          mv $file `basename $dir`${file[@]:`expr ${#file} - 4`}
        fi
      else

        if [ $count == 1 ]
        then
          mv `basename $dir`${file[@]:`expr ${#file} - 4`} `basename $dir`_0${file[@]:`expr ${#file} - 4`}
        fi

        mv $file `basename $dir`_$count${file[@]:`expr ${#file} - 4`}

      fi

      count=`expr $count + 1`

  done

  if [ $count == 0 ]
  then
    echo 'Nenhum arquivo descompactado'

  else
    srts=($(ls $dir/*.srt -d 2>/dev/null))

    count=0

    for srt in ${srts[@]}
    do

      if [ $count == 0 ]
      then
        cp $srt `basename $dir`${srt[@]:`expr ${#srt} - 4`}
      else

        if [ $count == 1 ]
        then
          mv `basename $dir`${srt[@]:`expr ${#srt} - 4`} `basename $dir`_0${srt[@]:`expr ${#srt} - 4`}
        fi

        cp $srt `basename $dir`_$count${srt[@]:`expr ${#srt} - 4`}

      fi

      count=`expr $count + 1`
    done
  fi
done

